version: '3.4'
#Ubuntu
services:
 ubuntu:
  build: ./ubuntu
  command: bash -c 'cmake .. | make | ctest | cat wins.txt'

#Centos
 centos:
  build: ./centos
  command: bash -c 'cmake .. | make | ctest | cat wins.txt'
