version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run:
          name: Install git
          command: git clone https://github.com/bsm52/devops_final_project.git

      - run:
          name: Print the Current Time
          command: date