version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install git
          command: sudo apt-get install git

      - run:
          name: Print the Current Time
          command: date