version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run: 
          name: Update and install git
          command: apt-get update && apt-get install -y git

      - run: 
          name: git clone project
          command: git clone https://github.com/bsm52/devops_final_project.git
          command: cd devops_final_project \
          command: ls

      - run:
          name: Print the Current Time
          command: date