version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run: 
          name: Update and install git
          command: apt-get update && apt-get install -y git

      - run:
          name: Print the Current Time
          command: date