version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run:
          name: Install git
          run: apt install git

      - run:
          name: Print the Current Time
          command: date