version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run: 
          name: Update and install g++, cmake
          command: apt-get update && apt-get install -y cmake && apt-get install g++

      - run: 
          name: make build dir
          command: mkdir build

      - run:
          name: cmake and make
          command: |
            cd build
            cmake ..
            make

    