version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run: 
          name: Update and install git
          command: apt-get update && apt-get install -y git

      - run: 
          name: git clone project and make build directory
          command: |
            git clone https://github.com/bsm52/devops_final_project.git
            cd devops_final_project
            mkdir build
            cd build

      - run:
          name: cmake
          command: cmake ..

      - run:
          name: make
          command: make